<div class="footer">
    <div class="footer-bottom">
        <div class="container">
            <div class="footer-bottom-inner">
                <div class="row">
                    <div class="col-sm-6 col-md-3">

                        <div id="properties_widget-3" class="widget widget_properties_widget">
                            <h2 class="widgettitle">	    Recent Properties	    </h2>

                            <div class="type-small">

                                <div class="property-small">
                                    <div class="property-small-image ">
                                        <a href="properties/lamb-dale/index.html">
                                            <img width="150" height="150" src="wp-content/uploads/2015/03/17-150x150.jpg" class="attachment-thumbnail size-thumbnail wp-post-image" alt="17" />            </a>
                                    </div><!-- /.property-small-image -->

                                    <div class="property-small-content">
                                        <h3 class="property-small-title">
                                            <a href="properties/lamb-dale/index.html">Lamb Dale</a>
                                        </h3><!-- /.property-small-title -->

                                        <div class="property-small-type">
                                            Villa			</div><!-- /.property-small-type -->

                                        <div class="property-small-price">
                                            $ 220,000			</div><!-- /.property-small-price -->
                                    </div><!-- /.property-small-content -->
                                </div><!-- /.property-small -->								
                                <div class="property-small">
                                    <div class="property-small-image ">
                                        <a href="properties/cotton-ridge/index.html">
                                            <img width="150" height="150" src="wp-content/uploads/2015/03/real-estate-11-150x150.jpg" class="attachment-thumbnail size-thumbnail wp-post-image" alt="real-estate-11" />            </a>
                                    </div><!-- /.property-small-image -->

                                    <div class="property-small-content">
                                        <h3 class="property-small-title">
                                            <a href="properties/cotton-ridge/index.html">Cotton Ridge</a>
                                        </h3><!-- /.property-small-title -->

                                        <div class="property-small-type">
                                            House			</div><!-- /.property-small-type -->

                                        <div class="property-small-price">
                                            $ 340,000			</div><!-- /.property-small-price -->
                                    </div><!-- /.property-small-content -->
                                </div><!-- /.property-small -->								
                                <div class="property-small">
                                    <div class="property-small-image ">
                                        <a href="properties/apricot-alcove/index.html">
                                            <img width="150" height="150" src="wp-content/uploads/2015/03/real-estate-13-150x150.jpg" class="attachment-thumbnail size-thumbnail wp-post-image" alt="real-estate-13" />            </a>
                                    </div><!-- /.property-small-image -->

                                    <div class="property-small-content">
                                        <h3 class="property-small-title">
                                            <a href="properties/apricot-alcove/index.html">Apricot Alcove</a>
                                        </h3><!-- /.property-small-title -->

                                        <div class="property-small-type">
                                            Apartment			</div><!-- /.property-small-type -->

                                        <div class="property-small-price">
                                            $ 125,000			</div><!-- /.property-small-price -->
                                    </div><!-- /.property-small-content -->
                                </div><!-- /.property-small -->									</div>

                        </div>                            </div>

                    <div class="col-sm-6 col-md-3">
                        <div id="nav_menu-2" class="widget widget_nav_menu"><h2 class="widgettitle">Quick Links</h2>
                            <div class="menu-quick-links-container"><ul id="menu-quick-links" class="menu"><li id="menu-item-68" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-68"><a href="http://preview.byaviators.com/">Homepage</a></li>
                                    <li id="menu-item-69" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-69"><a href="properties/index.html">Recent Properties</a></li>
                                    <li id="menu-item-70" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-70"><a href="agents/index.html">Our Agents</a></li>
                                    <li id="menu-item-71" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-71"><a href="agencies/index.html">Registered Agencies</a></li>
                                    <li id="menu-item-154" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-154"><a href="my-properties/index.html">My Properties</a></li>
                                    <li id="menu-item-155" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-155"><a href="blog-grid/index.html">Blog Grid</a></li>
                                    <li id="menu-item-72" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-72"><a href="contact/index.html">Contact Form</a></li>
                                </ul></div></div>                            </div>

                    <hr class="visible-sm">
                    <div class="col-sm-6 col-md-3">

                        <div id="agents_widget-3" class="widget widget_agents_widget">
                            <h2 class="widgettitle">	    Our Agents	    </h2>


                            <div class="agent-small">
                                <div class="agent-small-inner">
                                    <div class="agent-small-image">
                                        <a href="agents/john-redmond/index.html" class="agent-small-image-inner">

                                            <img width="270" height="270" src="wp-content/uploads/2015/02/male.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="male" />                            </a><!-- /.agent-small-image-inner -->
                                    </div><!-- /.agent-small-image -->

                                    <div class="agent-small-content">
                                        <h3 class="agent-small-title">
                                            <a href="agents/john-redmond/index.html">John Redmond</a>
                                        </h3>

                                        <div class="agent-small-email">
                                            <i class="fa fa-at"></i> <a href="agents/john-redmond/index.html">info@example.com</a>
                                        </div><!-- /.agent-small-email -->

                                        <div class="agent-small-phone">
                                            <i class="fa fa-phone"></i> +123-456-789                </div><!-- /.agent-small-phone -->
                                    </div><!-- /.agent-small-content -->
                                </div><!-- /.agent-small-inner -->
                            </div><!-- /.agent-small -->						
                            <div class="agent-small">
                                <div class="agent-small-inner">
                                    <div class="agent-small-image">
                                        <a href="agents/clare-collins/index.html" class="agent-small-image-inner">

                                            <img width="270" height="270" src="wp-content/uploads/2015/02/female.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="female" />                            </a><!-- /.agent-small-image-inner -->
                                    </div><!-- /.agent-small-image -->

                                    <div class="agent-small-content">
                                        <h3 class="agent-small-title">
                                            <a href="agents/clare-collins/index.html">Clare Collins</a>
                                        </h3>

                                        <div class="agent-small-email">
                                            <i class="fa fa-at"></i> <a href="agents/clare-collins/index.html">info@example.com</a>
                                        </div><!-- /.agent-small-email -->

                                        <div class="agent-small-phone">
                                            <i class="fa fa-phone"></i> +123-456-789                </div><!-- /.agent-small-phone -->
                                    </div><!-- /.agent-small-content -->
                                </div><!-- /.agent-small-inner -->
                            </div><!-- /.agent-small -->						
                            <div class="agent-small">
                                <div class="agent-small-inner">
                                    <div class="agent-small-image">
                                        <a href="agents/john-penning/index.html" class="agent-small-image-inner">

                                            <img width="270" height="270" src="wp-content/uploads/2015/02/male.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="male" />                            </a><!-- /.agent-small-image-inner -->
                                    </div><!-- /.agent-small-image -->

                                    <div class="agent-small-content">
                                        <h3 class="agent-small-title">
                                            <a href="agents/john-penning/index.html">John Penning</a>
                                        </h3>

                                        <div class="agent-small-email">
                                            <i class="fa fa-at"></i> <a href="agents/john-penning/index.html">info@example.com</a>
                                        </div><!-- /.agent-small-email -->

                                        <div class="agent-small-phone">
                                            <i class="fa fa-phone"></i> +123-456-789                </div><!-- /.agent-small-phone -->
                                    </div><!-- /.agent-small-content -->
                                </div><!-- /.agent-small-inner -->
                            </div><!-- /.agent-small -->						


                        </div>                            </div>

                    <div class="col-sm-6 col-md-3">
                        <div id="text-3" class="widget widget_text"><h2 class="widgettitle">Contact</h2>
                            <div class="textwidget"><table class="contact">
                                    <tbody>
                                        <tr>
                                            <th class="address"><i class="fa fa-map-marker"></i>Address:</th>
                                            <td>1900 Pico Blvd<br>Santa Monica, CA 90405<br>United States<br></td>
                                        </tr>
                                        <tr>
                                            <th class="phone"><i class="fa fa-phone"></i> Phone:</th>
                                            <td>+48 123 456 789</td>
                                        </tr>
                                        <tr>
                                            <th class="email"><i class="fa fa-at"></i> E-mail:</th>
                                            <td><a href="mailto:info@yourcompany.com">info@test.com</a></td>
                                        </tr>
                                        <tr>
                                            <th class="skype"><i class="fa fa-skype"></i> Skype:</th>
                                            <td>your.company</td>
                                        </tr>
                                    </tbody>
                                </table>

                                <ul class="social">
                                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                    <li><a href="#"><i class="fa fa-youtube"></i></a></li>
                                </ul></div>
                        </div>                            </div>

                </div><!-- /.row -->
            </div><!-- /.footer-bottom-inner -->
        </div><!-- /.container -->
    </div><!-- /.footer-bottom -->

    <div class="footer-bar">
        <div class="container center">
            <a class="scroll-top"><i class="fa fa-angle-up"></i></a>
        </div><!-- /.container -->
    </div><!-- /.footer-bar -->
</div><!-- /.footer -->