<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="msapplication-tap-highlight" content="no">
        <title><?php //echo $meta['title'];               ?></title>
        <meta name="keywords" content="<?php //echo $meta['keywords'];               ?>" />
        <meta name="description" content="<?php //echo $meta['description'];               ?>" />
        <meta name="author" content="Merab Chikvaidze">
        <base href="<?= $this->basePath(); ?>/skin/materialized/" />
        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
        <script>
//            $(document).ready(function () {
//                var accessToken = null;
//                $.ajaxSetup({cache: false});
//                $.getScript('//connect.facebook.net/en_US/sdk.js', function () {
//                    FB.init({
//                        appId: 1299069830149403,
//                        version: 'v2.8'
//                    });
//                    FB.getLoginStatus(statusChangeCallback);
//
//                    function statusChangeCallback(response) {
//                        if (response.status === 'connected') {                            
//                            accessToken = response.authResponse.accessToken;
//                            getInfo();
//                        } else if (response.status === 'not_authorized') {
//                            console.log("not_authorized");
//                        }
//                    }
//                    $("#logout").click(function () {
//                        FB.logout(function (response) {
//                            console.log(response);
//                        });
//                    });
//
//                    function getInfo() {
//                        FB.api('/me', function (response) {
//                            $.post('<?= $this->basePath(); ?>/fb/auth/save/',{id:response.id,name:response.name,atoken:accessToken},function(response){
//                                console.log(response);
//                            });
//                        });
//                    }
//                });
//            });
        </script>
    </head>
    <body>
        <button id="logout">Logout</button>
        <div class="fb-login-button" data-max-rows="1" data-size="medium" data-show-faces="false" data-auto-logout-link="false"></div>
        <?php
        echo $this->render('blocks/header.phtml');
        echo $this->content;
        echo $this->render('blocks/footer.phtml');
        echo $this->inlineScript();
        ?>
        <div id="fb-root"></div>
        <script>
//            (function (d, s, id) {
//                var js, fjs = d.getElementsByTagName(s)[0];
//                if (d.getElementById(id))
//                    return;
//                js = d.createElement(s);
//                js.id = id;
//                js.src = "//connect.facebook.net/ka_GE/sdk.js#xfbml=1&version=v2.8&appId=343808569161877";
//                fjs.parentNode.insertBefore(js, fjs);
//            }(document, 'script', 'facebook-jssdk'));
        </script>
    </body>
</html>